FROM dunglas/frankenphp:1-php8.4

RUN install-php-extensions pdo_mysql curl simplexml xml

WORKDIR /app

COPY docker/frankenphp/Caddyfile /etc/caddy/Caddyfile
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY . /app

ENV APP_ENV=prod \
    COMPOSER_ALLOW_SUPERUSER=1

RUN composer install --no-dev --optimize-autoloader --no-interaction --no-progress --no-scripts \
    && mkdir -p var/cache var/log \
    && chown -R www-data:www-data var

